### PR TITLE
Changes Tags

### PR DESCRIPTION
**Pull request by Somdotta07**
Header to H1 and H2

### CODE REVIEW

**Comment by Somdotta07** [comment]
Well done so far! There are some issues that you need to work !
## Required Changes ♻️
- [ ] **REQUIRED:** It will be nice to use the Microverse Professional Readme Template to design your README file (https://github.com/microverseinc/readme-template)
- [ ] **Optional :** 
 -You can use div under each section in your HTML file to get better .
-Try to add colors as given in the sample page

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial . However, strongly recommended to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

**Review by afanimartin — CHANGES_REQUESTED** [review]
Hi @Somdotta07, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [x] Always ask students to write descriptive PR stating what they did. This helps a reviewer paint a picture of what features have been built. Please point that out in your reviews as a requirement.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Somdotta07** [comment]
### Hello @Somdotta07  🙋‍♀️, 
Good job so far! 👌
#  Required Changes ♻️
- [ ] **REQUIRED:** It will be nice to use the Microverse Professional Readme Template to design your README file (https://github.com/microverseinc/readme-template)
- [ ] Add description to your PR to get better understanding of your project

- [ ] **Optional :** 
 -You can use div under each section in your HTML file to get better .
-Try to add colors as given in the sample page

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial . However, strongly recommended to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

**Review by oxenprogrammer — APPROVED** [review]
Hi @Somdotta07, 

Thank you for making the recommended changes.Your project is complete! It's time to merge it :shipit: 
Congratulations! 🎉 

**Optional Changes**
- [x] You should try to use inline comments where applicable. This helps to point to the person making the Pull Request to spot exactly where to make changes or where you applaud them for an excellent work done.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Somdotta07** [comment]
Thanks for the suggestion. I'll keep in mind.

**Pull request merged**
